### ISSUE TITLE
The bug of the code in main.py

### ISSUE THREAD

**Issue by XuemingQiu** [u784799i/biLSTM_attn#1]
when I tried to run your code, I have found some bugs.
The bugs are in main.py
def train function, return should be total_loss/training_data.sents_size not total_loss[0] /training_data.sents_size
similaritly, the def evaluate function ，return should be eval_loss/_size, not eval_loss[0]

my environments are 
python3.6 
pytorch 1.1.0 
torchvision 0.3.0

**Comment by foreversolar** [comment]
跟楼上差不多的问题

Traceback (most recent call last):File "main.py", line 119, in <module>loss = train()File "main.py", line 108, in trainreturn total_loss[0]/training_data.sents_sizeIndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Env：python3.6  pytorch 1.2.0

**Comment by greydog2020** [comment]
这不是bug，是pytorch版本问题，在新版本使用total_loss.item()代替total_loss[0]
